[tool.poetry]
name = "usovs"
version = "0.1.0"
description = "University Secure Online Voting System"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.3"
psycopg2-binary = "*"
firebase-admin = "*"
djangorestframework = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
