#!/usr/bin/env python3
"""Exit non-zero if coverage (line) is below threshold.

Reads coverage.xml (generated by `coverage xml -o coverage.xml`) and checks the
line-rate attribute on the root element. If not present, attempts to use
`lines-covered` and `lines-valid` attributes to compute percentage.
"""

import argparse
import sys
import xml.etree.ElementTree as ET


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument('--file', default='coverage.xml')
    p.add_argument('--threshold', type=float, required=True)
    return p.parse_args()


def get_coverage_from_xml(path):
    tree = ET.parse(path)
    root = tree.getroot()

    # Prefer line-rate attribute (fraction 0..1)
    line_rate = root.attrib.get('line-rate')
    if line_rate is not None:
        try:
            return float(line_rate) * 100.0
        except Exception:
            pass

    # Fallback: use lines-covered and lines-valid
    covered = root.attrib.get('lines-covered')
    valid = root.attrib.get('lines-valid')
    if covered is not None and valid is not None:
        try:
            covered = int(covered)
            valid = int(valid)
            return (covered / valid) * 100.0 if valid else 0.0
        except Exception:
            pass

    # Could not determine
    raise RuntimeError('Could not extract coverage percentage from XML')


def main():
    args = parse_args()
    try:
        pct = get_coverage_from_xml(args.file)
    except Exception as e:
        print(f'Error reading coverage file: {e}', file=sys.stderr)
        return 2

    print(f'Coverage: {pct:.2f}% (threshold: {args.threshold}%)')
    if pct + 1e-8 < args.threshold:
        print('Coverage below threshold', file=sys.stderr)
        return 1
    print('Coverage threshold satisfied')
    return 0


if __name__ == '__main__':
    sys.exit(main())
